# https://github.com/Azure/container-scan#ignoring-vulnerabilities
general:
  vulnerabilities:
    - CVE-2021-33574
    - CVE-2022-23218
    - CVE-2022-23219
    - CVE-2021-3999
    - CVE-2021-33560
    - CVE-2020-16156
    - CVE-2018-25032
#  bestPracticeViolations:
#    - CIS-DI-0001
#    - DKL-DI-0006
#    - CIS-DI-0006
#    - CIS-DI-0008 
